### ISSUE TITLE
RAM usage accumulates

### ISSUE THREAD

**Issue by yuandingding** [TomVeeDee/FoMo#11]
As the code runs, memory use accumulates and eventually lead to a kill by the system, owe to the shortage of RAM. Maybe memory is not released properly in the code.

**Comment by TomVeeDee** [comment]
Is this with the new version of the code (3.1/3.2), or rather with the old code that is still in the repository?

**Comment by TomVeeDee** [comment]
I have run valgrind on tag 3.3 (without CGAL and openmp) and that reports no memory leaks when using the NearestNeighbour method. 

CGAL and valgrind do not cooperate well, so for this method it is difficult to test memory leaks. 

I will assume that the memory leak is in an earlier version <3.1.
